#ifndef DNN_CONFIG_HPP_
#define DNN_CONFIG_HPP_

#define FLOAT                                                                 0

#define INPUT_MEM_WIDTH                                                       128
#define OUTPUT_MEM_WIDTH                                                      128
const int num_packed_inputs = 18432;
#define INPUT_SCALE                                                           0.0064476728439331055
#define INPUT_ZERO_POINT                                                      -16173
#define ACT_MIN_VALUE                                                         -32768
#define ACT_MAX_VALUE                                                         32767
#define INPUT_DIM                                                             128
#define INPUT_CH                                                              18
#define INPUT_BITS                                                            16
typedef ap_int<INPUT_BITS> INPUT_dtype;

#define CONV_LAYER_0_K                                                        3
#define CONV_LAYER_0_IFM_CH                                                   18
#define CONV_LAYER_0_IFM_DIM                                                  128
#define CONV_LAYER_0_OFM_CH                                                   16
#define CONV_LAYER_0_OFM_DIM                                                  128
#define CONV_LAYER_0_GROUPS                                                   1
#define CONV_LAYER_0_STRIDE                                                   1
#define CONV_LAYER_0_PADDING                                                  1
#define CONV_LAYER_0_SIMD                                                     2
#define CONV_LAYER_0_PE                                                       8
#define CONV_LAYER_0_IFM_BITS                                                 16
#define CONV_LAYER_0_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_0_INPUT_STREAM_WIDTH                                       32
#define CONV_LAYER_0_INPUT_MEM_WIDTH                                          32
#define CONV_LAYER_0_INPUT_ACCESSESS                                          147456
#define CONV_LAYER_0_WEIGHT_BITS                                              16
#define CONV_LAYER_0_WEIGHT_SIMD_WIDTH                                        32
#define CONV_LAYER_0_WEIGHT_SIMD_PE_WIDTH                                     256
#define CONV_LAYER_0_BIAS_BITS                                                32
#define CONV_LAYER_0_ACC_BITS                                                 34
#define CONV_LAYER_0_ATILES                                                   2
#define CONV_LAYER_0_WTILES                                                   162
#define CONV_LAYER_0_OFM_BITS                                                 16
#define CONV_LAYER_0_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_0_OUTPUT_STREAM_WIDTH                                      128
#define CONV_LAYER_0_OUTPUT_MEM_WIDTH                                         128
#define CONV_LAYER_0_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_0_M0                                                       1.9631417671917006e-05
#define CONV_LAYER_0_M0_BITS                                                  32
#define CONV_LAYER_0_M0_INT_BITS                                              -4
#define CONV_LAYER_0_INPUT_ZERO_POINT                                         -16173
#define CONV_LAYER_0_OUTPUT_ZERO_POINT                                        -32768
typedef ap_int<CONV_LAYER_0_IFM_BITS> conv_layer_0_input_dtype;
typedef ap_int<CONV_LAYER_0_WEIGHT_BITS> conv_layer_0_weight_dtype;
typedef ap_int<CONV_LAYER_0_BIAS_BITS> conv_layer_0_bias_dtype;
typedef ap_int<CONV_LAYER_0_ACC_BITS> conv_layer_0_acc_dtype;
typedef ap_int<CONV_LAYER_0_OFM_BITS> conv_layer_0_output_dtype;
typedef ap_ufixed<CONV_LAYER_0_M0_BITS, CONV_LAYER_0_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_0_m0_dtype;

#define CONV_LAYER_1_K                                                        3
#define CONV_LAYER_1_IFM_CH                                                   16
#define CONV_LAYER_1_IFM_DIM                                                  128
#define CONV_LAYER_1_OFM_CH                                                   16
#define CONV_LAYER_1_OFM_DIM                                                  128
#define CONV_LAYER_1_GROUPS                                                   1
#define CONV_LAYER_1_STRIDE                                                   1
#define CONV_LAYER_1_PADDING                                                  1
#define CONV_LAYER_1_SIMD                                                     4
#define CONV_LAYER_1_PE                                                       4
#define CONV_LAYER_1_IFM_BITS                                                 16
#define CONV_LAYER_1_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_1_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_1_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_1_INPUT_ACCESSESS                                          65536
#define CONV_LAYER_1_WEIGHT_BITS                                              16
#define CONV_LAYER_1_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_1_WEIGHT_SIMD_PE_WIDTH                                     256
#define CONV_LAYER_1_BIAS_BITS                                                32
#define CONV_LAYER_1_ACC_BITS                                                 34
#define CONV_LAYER_1_ATILES                                                   4
#define CONV_LAYER_1_WTILES                                                   144
#define CONV_LAYER_1_OFM_BITS                                                 16
#define CONV_LAYER_1_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_1_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_1_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_1_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_1_M0                                                       2.1438952899188735e-05
#define CONV_LAYER_1_M0_BITS                                                  32
#define CONV_LAYER_1_M0_INT_BITS                                              -4
#define CONV_LAYER_1_INPUT_ZERO_POINT                                         -32768
#define CONV_LAYER_1_OUTPUT_ZERO_POINT                                        -32768
typedef ap_int<CONV_LAYER_1_IFM_BITS> conv_layer_1_input_dtype;
typedef ap_int<CONV_LAYER_1_WEIGHT_BITS> conv_layer_1_weight_dtype;
typedef ap_int<CONV_LAYER_1_BIAS_BITS> conv_layer_1_bias_dtype;
typedef ap_int<CONV_LAYER_1_ACC_BITS> conv_layer_1_acc_dtype;
typedef ap_int<CONV_LAYER_1_OFM_BITS> conv_layer_1_output_dtype;
typedef ap_ufixed<CONV_LAYER_1_M0_BITS, CONV_LAYER_1_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_1_m0_dtype;

#define SPLIT_0_SIMD                                                          1
#define SPLIT_0_PE                                                            1
#define SPLIT_0_IFM_BITS                                                      16
#define SPLIT_0_IFM_BITS_ALIGNED                                              16
#define SPLIT_0_INPUT_STREAM_WIDTH                                            16
#define SPLIT_0_INPUT_MEM_WIDTH                                               16
#define SPLIT_0_INPUT_ACCESSESS                                               262144
#define SPLIT_0_OFM_BITS                                                      16
#define SPLIT_0_OFM_BITS_ALIGNED                                              16
#define SPLIT_0_OUTPUT_STREAM_WIDTH                                           16
#define SPLIT_0_OUTPUT_MEM_WIDTH                                              16
#define SPLIT_0_OUTPUT_ACCESSES                                               262144
typedef ap_int<SPLIT_0_IFM_BITS> split_0_input_dtype;
typedef ap_int<SPLIT_0_OFM_BITS> split_0_output_dtype;

#define MAXPOOL_0_SIMD                                                        1
#define MAXPOOL_0_PE                                                          1
#define MAXPOOL_0_K                                                           2
#define MAXPOOL_0_STRIDE                                                      2
#define MAXPOOL_0_IFM_CH                                                      16
#define MAXPOOL_0_IFM_DIM                                                     128
#define MAXPOOL_0_OFM_CH                                                      16
#define MAXPOOL_0_OFM_DIM                                                     64
#define MAXPOOL_0_IFM_BITS                                                    16
#define MAXPOOL_0_IFM_BITS_ALIGNED                                            16
#define MAXPOOL_0_INPUT_STREAM_WIDTH                                          16
#define MAXPOOL_0_INPUT_MEM_WIDTH                                             16
#define MAXPOOL_0_INPUT_ACCESSESS                                             262144
#define MAXPOOL_0_OFM_BITS                                                    16
#define MAXPOOL_0_OFM_BITS_ALIGNED                                            16
#define MAXPOOL_0_OUTPUT_STREAM_WIDTH                                         16
#define MAXPOOL_0_OUTPUT_MEM_WIDTH                                            16
#define MAXPOOL_0_OUTPUT_ACCESSES                                             65536
typedef ap_int<MAXPOOL_0_IFM_BITS> maxpool_0_input_dtype;
typedef ap_int<MAXPOOL_0_OFM_BITS> maxpool_0_output_dtype;

#define CONV_LAYER_2_K                                                        3
#define CONV_LAYER_2_IFM_CH                                                   16
#define CONV_LAYER_2_IFM_DIM                                                  64
#define CONV_LAYER_2_OFM_CH                                                   16
#define CONV_LAYER_2_OFM_DIM                                                  64
#define CONV_LAYER_2_GROUPS                                                   1
#define CONV_LAYER_2_STRIDE                                                   1
#define CONV_LAYER_2_PADDING                                                  1
#define CONV_LAYER_2_SIMD                                                     2
#define CONV_LAYER_2_PE                                                       2
#define CONV_LAYER_2_IFM_BITS                                                 16
#define CONV_LAYER_2_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_2_INPUT_STREAM_WIDTH                                       32
#define CONV_LAYER_2_INPUT_MEM_WIDTH                                          32
#define CONV_LAYER_2_INPUT_ACCESSESS                                          32768
#define CONV_LAYER_2_WEIGHT_BITS                                              16
#define CONV_LAYER_2_WEIGHT_SIMD_WIDTH                                        32
#define CONV_LAYER_2_WEIGHT_SIMD_PE_WIDTH                                     64
#define CONV_LAYER_2_BIAS_BITS                                                32
#define CONV_LAYER_2_ACC_BITS                                                 34
#define CONV_LAYER_2_ATILES                                                   8
#define CONV_LAYER_2_WTILES                                                   576
#define CONV_LAYER_2_OFM_BITS                                                 16
#define CONV_LAYER_2_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_2_OUTPUT_STREAM_WIDTH                                      32
#define CONV_LAYER_2_OUTPUT_MEM_WIDTH                                         32
#define CONV_LAYER_2_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_2_M0                                                       6.819707778049633e-06
#define CONV_LAYER_2_M0_BITS                                                  32
#define CONV_LAYER_2_M0_INT_BITS                                              -5
#define CONV_LAYER_2_INPUT_ZERO_POINT                                         -32768
#define CONV_LAYER_2_OUTPUT_ZERO_POINT                                        -32768
typedef ap_int<CONV_LAYER_2_IFM_BITS> conv_layer_2_input_dtype;
typedef ap_int<CONV_LAYER_2_WEIGHT_BITS> conv_layer_2_weight_dtype;
typedef ap_int<CONV_LAYER_2_BIAS_BITS> conv_layer_2_bias_dtype;
typedef ap_int<CONV_LAYER_2_ACC_BITS> conv_layer_2_acc_dtype;
typedef ap_int<CONV_LAYER_2_OFM_BITS> conv_layer_2_output_dtype;
typedef ap_ufixed<CONV_LAYER_2_M0_BITS, CONV_LAYER_2_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_2_m0_dtype;

#define CONV_LAYER_3_K                                                        3
#define CONV_LAYER_3_IFM_CH                                                   16
#define CONV_LAYER_3_IFM_DIM                                                  64
#define CONV_LAYER_3_OFM_CH                                                   16
#define CONV_LAYER_3_OFM_DIM                                                  64
#define CONV_LAYER_3_GROUPS                                                   1
#define CONV_LAYER_3_STRIDE                                                   1
#define CONV_LAYER_3_PADDING                                                  1
#define CONV_LAYER_3_SIMD                                                     2
#define CONV_LAYER_3_PE                                                       2
#define CONV_LAYER_3_IFM_BITS                                                 16
#define CONV_LAYER_3_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_3_INPUT_STREAM_WIDTH                                       32
#define CONV_LAYER_3_INPUT_MEM_WIDTH                                          32
#define CONV_LAYER_3_INPUT_ACCESSESS                                          32768
#define CONV_LAYER_3_WEIGHT_BITS                                              16
#define CONV_LAYER_3_WEIGHT_SIMD_WIDTH                                        32
#define CONV_LAYER_3_WEIGHT_SIMD_PE_WIDTH                                     64
#define CONV_LAYER_3_BIAS_BITS                                                32
#define CONV_LAYER_3_ACC_BITS                                                 34
#define CONV_LAYER_3_ATILES                                                   8
#define CONV_LAYER_3_WTILES                                                   576
#define CONV_LAYER_3_OFM_BITS                                                 16
#define CONV_LAYER_3_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_3_OUTPUT_STREAM_WIDTH                                      32
#define CONV_LAYER_3_OUTPUT_MEM_WIDTH                                         32
#define CONV_LAYER_3_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_3_M0                                                       1.603259443072602e-05
#define CONV_LAYER_3_M0_BITS                                                  32
#define CONV_LAYER_3_M0_INT_BITS                                              -4
#define CONV_LAYER_3_INPUT_ZERO_POINT                                         -32768
#define CONV_LAYER_3_OUTPUT_ZERO_POINT                                        -32768
typedef ap_int<CONV_LAYER_3_IFM_BITS> conv_layer_3_input_dtype;
typedef ap_int<CONV_LAYER_3_WEIGHT_BITS> conv_layer_3_weight_dtype;
typedef ap_int<CONV_LAYER_3_BIAS_BITS> conv_layer_3_bias_dtype;
typedef ap_int<CONV_LAYER_3_ACC_BITS> conv_layer_3_acc_dtype;
typedef ap_int<CONV_LAYER_3_OFM_BITS> conv_layer_3_output_dtype;
typedef ap_ufixed<CONV_LAYER_3_M0_BITS, CONV_LAYER_3_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_3_m0_dtype;

#define CONVTRANSPOSE_0_K                                                     2
#define CONVTRANSPOSE_0_IFM_CH                                                16
#define CONVTRANSPOSE_0_IFM_DIM                                               64
#define CONVTRANSPOSE_0_OFM_CH                                                16
#define CONVTRANSPOSE_0_OFM_DIM                                               128
#define CONVTRANSPOSE_0_GROUPS                                                1
#define CONVTRANSPOSE_0_STRIDE                                                2
#define CONVTRANSPOSE_0_PADDING                                               0
#define CONVTRANSPOSE_0_SIMD                                                  1
#define CONVTRANSPOSE_0_PE                                                    1
#define CONVTRANSPOSE_0_IFM_BITS                                              16
#define CONVTRANSPOSE_0_IFM_BITS_ALIGNED                                      16
#define CONVTRANSPOSE_0_INPUT_STREAM_WIDTH                                    16
#define CONVTRANSPOSE_0_INPUT_MEM_WIDTH                                       16
#define CONVTRANSPOSE_0_INPUT_ACCESSESS                                       65536
#define CONVTRANSPOSE_0_WEIGHT_BITS                                           16
#define CONVTRANSPOSE_0_WEIGHT_SIMD_WIDTH                                     16
#define CONVTRANSPOSE_0_WEIGHT_SIMD_PE_WIDTH                                  16
#define CONVTRANSPOSE_0_BIAS_BITS                                             32
#define CONVTRANSPOSE_0_ACC_BITS                                              34
#define CONVTRANSPOSE_0_ATILES                                                16
#define CONVTRANSPOSE_0_WTILES                                                1024
#define CONVTRANSPOSE_0_OFM_BITS                                              16
#define CONVTRANSPOSE_0_OFM_BITS_ALIGNED                                      16
#define CONVTRANSPOSE_0_OUTPUT_STREAM_WIDTH                                   16
#define CONVTRANSPOSE_0_OUTPUT_MEM_WIDTH                                      16
#define CONVTRANSPOSE_0_OUTPUT_ACCESSES                                       262144
#define CONVTRANSPOSE_0_M0                                                    2.0083210984012112e-05
#define CONVTRANSPOSE_0_M0_BITS                                               32
#define CONVTRANSPOSE_0_M0_INT_BITS                                           -4
#define CONVTRANSPOSE_0_INPUT_ZERO_POINT                                      -32768
#define CONVTRANSPOSE_0_OUTPUT_ZERO_POINT                                     -32768
typedef ap_int<CONVTRANSPOSE_0_IFM_BITS> convtranspose_0_input_dtype;
typedef ap_int<CONVTRANSPOSE_0_WEIGHT_BITS> convtranspose_0_weight_dtype;
typedef ap_int<CONVTRANSPOSE_0_BIAS_BITS> convtranspose_0_bias_dtype;
typedef ap_int<CONVTRANSPOSE_0_ACC_BITS> convtranspose_0_acc_dtype;
typedef ap_int<CONVTRANSPOSE_0_OFM_BITS> convtranspose_0_output_dtype;
typedef ap_ufixed<CONVTRANSPOSE_0_M0_BITS, CONVTRANSPOSE_0_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> convtranspose_0_m0_dtype;

#define CONCAT_0_SIMD                                                         1
#define CONCAT_0_PE                                                           1
#define CONCAT_0_IFM_CH                                                       16
#define CONCAT_0_IFM_DIM                                                      128
#define CONCAT_0_IFM_BITS                                                     16
#define CONCAT_0_OFM_BITS                                                     16
#define CONCAT_0_INPUT_STREAM_WIDTH                                           16
#define CONCAT_0_OFM_BITS_ALIGNED                                             32
#define CONCAT_0_OUTPUT_STREAM_WIDTH                                          16
#define CONCAT_0_OUTPUT_ACCESSES                                              524288
#define CONCAT_0_0_M0                                                         0.016253378242254257
#define CONCAT_0_0_INPUT_ZERO_POINT                                           -32235.409301757812
#define CONCAT_0_1_M0                                                         1.0
#define CONCAT_0_1_INPUT_ZERO_POINT                                           0.0
#define CONCAT_0_SCALE_BITS                                                   32
#define CONCAT_0_SCALE_INT_BITS                                               1
#define CONCAT_0_SHIFT_BITS                                                   32
#define CONCAT_0_SHIFT_INT_BITS                                               16
typedef ap_ufixed<CONCAT_0_SCALE_BITS,CONCAT_0_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_0_scale_dtype;
typedef ap_fixed<CONCAT_0_SHIFT_BITS,CONCAT_0_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_0_shift_dtype;
typedef ap_int<CONCAT_0_IFM_BITS> concat_0_input_dtype;
typedef ap_int<CONCAT_0_OFM_BITS> concat_0_output_dtype;

#define CONV_LAYER_4_K                                                        3
#define CONV_LAYER_4_IFM_CH                                                   32
#define CONV_LAYER_4_IFM_DIM                                                  128
#define CONV_LAYER_4_OFM_CH                                                   16
#define CONV_LAYER_4_OFM_DIM                                                  128
#define CONV_LAYER_4_GROUPS                                                   1
#define CONV_LAYER_4_STRIDE                                                   1
#define CONV_LAYER_4_PADDING                                                  1
#define CONV_LAYER_4_SIMD                                                     4
#define CONV_LAYER_4_PE                                                       4
#define CONV_LAYER_4_IFM_BITS                                                 16
#define CONV_LAYER_4_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_4_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_4_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_4_INPUT_ACCESSESS                                          131072
#define CONV_LAYER_4_WEIGHT_BITS                                              16
#define CONV_LAYER_4_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_4_WEIGHT_SIMD_PE_WIDTH                                     256
#define CONV_LAYER_4_BIAS_BITS                                                32
#define CONV_LAYER_4_ACC_BITS                                                 34
#define CONV_LAYER_4_ATILES                                                   4
#define CONV_LAYER_4_WTILES                                                   288
#define CONV_LAYER_4_OFM_BITS                                                 16
#define CONV_LAYER_4_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_4_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_4_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_4_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_4_M0                                                       1.9315461031510495e-05
#define CONV_LAYER_4_M0_BITS                                                  32
#define CONV_LAYER_4_M0_INT_BITS                                              -4
#define CONV_LAYER_4_INPUT_ZERO_POINT                                         -32768
#define CONV_LAYER_4_OUTPUT_ZERO_POINT                                        -32768
typedef ap_int<CONV_LAYER_4_IFM_BITS> conv_layer_4_input_dtype;
typedef ap_int<CONV_LAYER_4_WEIGHT_BITS> conv_layer_4_weight_dtype;
typedef ap_int<CONV_LAYER_4_BIAS_BITS> conv_layer_4_bias_dtype;
typedef ap_int<CONV_LAYER_4_ACC_BITS> conv_layer_4_acc_dtype;
typedef ap_int<CONV_LAYER_4_OFM_BITS> conv_layer_4_output_dtype;
typedef ap_ufixed<CONV_LAYER_4_M0_BITS, CONV_LAYER_4_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_4_m0_dtype;

#define CONV_LAYER_5_K                                                        3
#define CONV_LAYER_5_IFM_CH                                                   16
#define CONV_LAYER_5_IFM_DIM                                                  128
#define CONV_LAYER_5_OFM_CH                                                   16
#define CONV_LAYER_5_OFM_DIM                                                  128
#define CONV_LAYER_5_GROUPS                                                   1
#define CONV_LAYER_5_STRIDE                                                   1
#define CONV_LAYER_5_PADDING                                                  1
#define CONV_LAYER_5_SIMD                                                     4
#define CONV_LAYER_5_PE                                                       4
#define CONV_LAYER_5_IFM_BITS                                                 16
#define CONV_LAYER_5_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_5_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_5_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_5_INPUT_ACCESSESS                                          65536
#define CONV_LAYER_5_WEIGHT_BITS                                              16
#define CONV_LAYER_5_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_5_WEIGHT_SIMD_PE_WIDTH                                     256
#define CONV_LAYER_5_BIAS_BITS                                                32
#define CONV_LAYER_5_ACC_BITS                                                 34
#define CONV_LAYER_5_ATILES                                                   4
#define CONV_LAYER_5_WTILES                                                   144
#define CONV_LAYER_5_OFM_BITS                                                 16
#define CONV_LAYER_5_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_5_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_5_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_5_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_5_M0                                                       1.3445024706015829e-05
#define CONV_LAYER_5_M0_BITS                                                  32
#define CONV_LAYER_5_M0_INT_BITS                                              -4
#define CONV_LAYER_5_INPUT_ZERO_POINT                                         -32768
#define CONV_LAYER_5_OUTPUT_ZERO_POINT                                        -32768
typedef ap_int<CONV_LAYER_5_IFM_BITS> conv_layer_5_input_dtype;
typedef ap_int<CONV_LAYER_5_WEIGHT_BITS> conv_layer_5_weight_dtype;
typedef ap_int<CONV_LAYER_5_BIAS_BITS> conv_layer_5_bias_dtype;
typedef ap_int<CONV_LAYER_5_ACC_BITS> conv_layer_5_acc_dtype;
typedef ap_int<CONV_LAYER_5_OFM_BITS> conv_layer_5_output_dtype;
typedef ap_ufixed<CONV_LAYER_5_M0_BITS, CONV_LAYER_5_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_5_m0_dtype;

#define CONV_LAYER_6_K                                                        1
#define CONV_LAYER_6_IFM_CH                                                   16
#define CONV_LAYER_6_IFM_DIM                                                  128
#define CONV_LAYER_6_OFM_CH                                                   2
#define CONV_LAYER_6_OFM_DIM                                                  128
#define CONV_LAYER_6_GROUPS                                                   1
#define CONV_LAYER_6_STRIDE                                                   1
#define CONV_LAYER_6_PADDING                                                  0
#define CONV_LAYER_6_SIMD                                                     1
#define CONV_LAYER_6_PE                                                       1
#define CONV_LAYER_6_IFM_BITS                                                 16
#define CONV_LAYER_6_IFM_BITS_ALIGNED                                         16
#define CONV_LAYER_6_INPUT_STREAM_WIDTH                                       16
#define CONV_LAYER_6_INPUT_MEM_WIDTH                                          16
#define CONV_LAYER_6_INPUT_ACCESSESS                                          262144
#define CONV_LAYER_6_WEIGHT_BITS                                              16
#define CONV_LAYER_6_WEIGHT_SIMD_WIDTH                                        16
#define CONV_LAYER_6_WEIGHT_SIMD_PE_WIDTH                                     16
#define CONV_LAYER_6_BIAS_BITS                                                32
#define CONV_LAYER_6_ACC_BITS                                                 34
#define CONV_LAYER_6_ATILES                                                   2
#define CONV_LAYER_6_WTILES                                                   32
#define CONV_LAYER_6_OFM_BITS                                                 16
#define CONV_LAYER_6_OFM_BITS_ALIGNED                                         16
#define CONV_LAYER_6_OUTPUT_STREAM_WIDTH                                      16
#define CONV_LAYER_6_OUTPUT_MEM_WIDTH                                         16
#define CONV_LAYER_6_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_6_M0                                                       1.2573258572956547e-05
#define CONV_LAYER_6_M0_BITS                                                  32
#define CONV_LAYER_6_M0_INT_BITS                                              -4
#define CONV_LAYER_6_INPUT_ZERO_POINT                                         -32768
#define CONV_LAYER_6_OUTPUT_ZERO_POINT                                        -5303
typedef ap_int<CONV_LAYER_6_IFM_BITS> conv_layer_6_input_dtype;
typedef ap_int<CONV_LAYER_6_WEIGHT_BITS> conv_layer_6_weight_dtype;
typedef ap_int<CONV_LAYER_6_BIAS_BITS> conv_layer_6_bias_dtype;
typedef ap_int<CONV_LAYER_6_ACC_BITS> conv_layer_6_acc_dtype;
typedef ap_int<CONV_LAYER_6_OFM_BITS> conv_layer_6_output_dtype;
typedef ap_ufixed<CONV_LAYER_6_M0_BITS, CONV_LAYER_6_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_6_m0_dtype;

const int num_packed_outputs = 4096;
#define CONV_LAYER_6_TOP_LEVEL_OUTPUT_BITS                                    16
typedef ap_int<CONV_LAYER_6_TOP_LEVEL_OUTPUT_BITS> conv_layer_6_top_level_output_dtype;

#define Reps 1


#endif