#ifndef DNN_CONFIG_HPP_
#define DNN_CONFIG_HPP_

#define FLOAT                                                                 0

#define INPUT_MEM_WIDTH                                                       128
#define OUTPUT_MEM_WIDTH                                                      128
const int num_packed_inputs = 9216;
#define INPUT_SCALE                                                           0.009468217380344868
#define INPUT_ZERO_POINT                                                      -45
#define ACT_MIN_VALUE                                                         -128
#define ACT_MAX_VALUE                                                         127
#define INPUT_DIM                                                             128
#define INPUT_CH                                                              9
#define INPUT_BITS                                                            8
typedef ap_int<INPUT_BITS> INPUT_dtype;

#define CONV_LAYER_0_K                                                        3
#define CONV_LAYER_0_IFM_CH                                                   9
#define CONV_LAYER_0_IFM_DIM                                                  128
#define CONV_LAYER_0_OFM_CH                                                   32
#define CONV_LAYER_0_OFM_DIM                                                  128
#define CONV_LAYER_0_GROUPS                                                   1
#define CONV_LAYER_0_STRIDE                                                   1
#define CONV_LAYER_0_PADDING                                                  1
#define CONV_LAYER_0_SIMD                                                     1
#define CONV_LAYER_0_PE                                                       8
#define CONV_LAYER_0_IFM_BITS                                                 8
#define CONV_LAYER_0_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_0_INPUT_STREAM_WIDTH                                       8
#define CONV_LAYER_0_INPUT_MEM_WIDTH                                          8
#define CONV_LAYER_0_INPUT_ACCESSESS                                          147456
#define CONV_LAYER_0_WEIGHT_BITS                                              8
#define CONV_LAYER_0_WEIGHT_SIMD_WIDTH                                        8
#define CONV_LAYER_0_WEIGHT_SIMD_PE_WIDTH                                     64
#define CONV_LAYER_0_BIAS_BITS                                                32
#define CONV_LAYER_0_ACC_BITS                                                 32
#define CONV_LAYER_0_ATILES                                                   4
#define CONV_LAYER_0_WTILES                                                   324
#define CONV_LAYER_0_OFM_BITS                                                 8
#define CONV_LAYER_0_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_0_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_0_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_0_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_0_M0                                                       0.0030043029692023993
#define CONV_LAYER_0_M0_BITS                                                  32
#define CONV_LAYER_0_M0_INT_BITS                                              -2
#define CONV_LAYER_0_INPUT_ZERO_POINT                                         -45
#define CONV_LAYER_0_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_0_IFM_BITS> conv_layer_0_input_dtype;
typedef ap_int<CONV_LAYER_0_WEIGHT_BITS> conv_layer_0_weight_dtype;
typedef ap_int<CONV_LAYER_0_BIAS_BITS> conv_layer_0_bias_dtype;
typedef ap_int<CONV_LAYER_0_ACC_BITS> conv_layer_0_acc_dtype;
typedef ap_int<CONV_LAYER_0_OFM_BITS> conv_layer_0_output_dtype;
typedef ap_ufixed<CONV_LAYER_0_M0_BITS, CONV_LAYER_0_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_0_m0_dtype;

#define CONV_LAYER_1_K                                                        3
#define CONV_LAYER_1_IFM_CH                                                   32
#define CONV_LAYER_1_IFM_DIM                                                  128
#define CONV_LAYER_1_OFM_CH                                                   32
#define CONV_LAYER_1_OFM_DIM                                                  128
#define CONV_LAYER_1_GROUPS                                                   1
#define CONV_LAYER_1_STRIDE                                                   1
#define CONV_LAYER_1_PADDING                                                  1
#define CONV_LAYER_1_SIMD                                                     8
#define CONV_LAYER_1_PE                                                       8
#define CONV_LAYER_1_IFM_BITS                                                 8
#define CONV_LAYER_1_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_1_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_1_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_1_INPUT_ACCESSESS                                          65536
#define CONV_LAYER_1_WEIGHT_BITS                                              8
#define CONV_LAYER_1_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_1_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_1_BIAS_BITS                                                32
#define CONV_LAYER_1_ACC_BITS                                                 32
#define CONV_LAYER_1_ATILES                                                   4
#define CONV_LAYER_1_WTILES                                                   144
#define CONV_LAYER_1_OFM_BITS                                                 8
#define CONV_LAYER_1_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_1_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_1_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_1_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_1_M0                                                       0.0009167162352241576
#define CONV_LAYER_1_M0_BITS                                                  32
#define CONV_LAYER_1_M0_INT_BITS                                              -3
#define CONV_LAYER_1_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_1_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_1_IFM_BITS> conv_layer_1_input_dtype;
typedef ap_int<CONV_LAYER_1_WEIGHT_BITS> conv_layer_1_weight_dtype;
typedef ap_int<CONV_LAYER_1_BIAS_BITS> conv_layer_1_bias_dtype;
typedef ap_int<CONV_LAYER_1_ACC_BITS> conv_layer_1_acc_dtype;
typedef ap_int<CONV_LAYER_1_OFM_BITS> conv_layer_1_output_dtype;
typedef ap_ufixed<CONV_LAYER_1_M0_BITS, CONV_LAYER_1_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_1_m0_dtype;

#define SPLIT_0_SIMD                                                          1
#define SPLIT_0_PE                                                            1
#define SPLIT_0_IFM_BITS                                                      8
#define SPLIT_0_IFM_BITS_ALIGNED                                              8
#define SPLIT_0_INPUT_STREAM_WIDTH                                            8
#define SPLIT_0_INPUT_MEM_WIDTH                                               8
#define SPLIT_0_INPUT_ACCESSESS                                               524288
#define SPLIT_0_OFM_BITS                                                      8
#define SPLIT_0_OFM_BITS_ALIGNED                                              8
#define SPLIT_0_OUTPUT_STREAM_WIDTH                                           8
#define SPLIT_0_OUTPUT_MEM_WIDTH                                              8
#define SPLIT_0_OUTPUT_ACCESSES                                               524288
typedef ap_int<SPLIT_0_IFM_BITS> split_0_input_dtype;
typedef ap_int<SPLIT_0_OFM_BITS> split_0_output_dtype;

#define MAXPOOL_0_SIMD                                                        1
#define MAXPOOL_0_PE                                                          1
#define MAXPOOL_0_K                                                           2
#define MAXPOOL_0_STRIDE                                                      2
#define MAXPOOL_0_IFM_CH                                                      32
#define MAXPOOL_0_IFM_DIM                                                     128
#define MAXPOOL_0_OFM_CH                                                      32
#define MAXPOOL_0_OFM_DIM                                                     64
#define MAXPOOL_0_IFM_BITS                                                    8
#define MAXPOOL_0_IFM_BITS_ALIGNED                                            8
#define MAXPOOL_0_INPUT_STREAM_WIDTH                                          8
#define MAXPOOL_0_INPUT_MEM_WIDTH                                             8
#define MAXPOOL_0_INPUT_ACCESSESS                                             524288
#define MAXPOOL_0_OFM_BITS                                                    8
#define MAXPOOL_0_OFM_BITS_ALIGNED                                            8
#define MAXPOOL_0_OUTPUT_STREAM_WIDTH                                         8
#define MAXPOOL_0_OUTPUT_MEM_WIDTH                                            8
#define MAXPOOL_0_OUTPUT_ACCESSES                                             131072
typedef ap_int<MAXPOOL_0_IFM_BITS> maxpool_0_input_dtype;
typedef ap_int<MAXPOOL_0_OFM_BITS> maxpool_0_output_dtype;

#define CONV_LAYER_2_K                                                        3
#define CONV_LAYER_2_IFM_CH                                                   32
#define CONV_LAYER_2_IFM_DIM                                                  64
#define CONV_LAYER_2_OFM_CH                                                   64
#define CONV_LAYER_2_OFM_DIM                                                  64
#define CONV_LAYER_2_GROUPS                                                   1
#define CONV_LAYER_2_STRIDE                                                   1
#define CONV_LAYER_2_PADDING                                                  1
#define CONV_LAYER_2_SIMD                                                     4
#define CONV_LAYER_2_PE                                                       4
#define CONV_LAYER_2_IFM_BITS                                                 8
#define CONV_LAYER_2_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_2_INPUT_STREAM_WIDTH                                       32
#define CONV_LAYER_2_INPUT_MEM_WIDTH                                          32
#define CONV_LAYER_2_INPUT_ACCESSESS                                          32768
#define CONV_LAYER_2_WEIGHT_BITS                                              8
#define CONV_LAYER_2_WEIGHT_SIMD_WIDTH                                        32
#define CONV_LAYER_2_WEIGHT_SIMD_PE_WIDTH                                     128
#define CONV_LAYER_2_BIAS_BITS                                                32
#define CONV_LAYER_2_ACC_BITS                                                 32
#define CONV_LAYER_2_ATILES                                                   16
#define CONV_LAYER_2_WTILES                                                   1152
#define CONV_LAYER_2_OFM_BITS                                                 8
#define CONV_LAYER_2_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_2_OUTPUT_STREAM_WIDTH                                      32
#define CONV_LAYER_2_OUTPUT_MEM_WIDTH                                         32
#define CONV_LAYER_2_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_2_M0                                                       0.0012955756392329931
#define CONV_LAYER_2_M0_BITS                                                  32
#define CONV_LAYER_2_M0_INT_BITS                                              -2
#define CONV_LAYER_2_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_2_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_2_IFM_BITS> conv_layer_2_input_dtype;
typedef ap_int<CONV_LAYER_2_WEIGHT_BITS> conv_layer_2_weight_dtype;
typedef ap_int<CONV_LAYER_2_BIAS_BITS> conv_layer_2_bias_dtype;
typedef ap_int<CONV_LAYER_2_ACC_BITS> conv_layer_2_acc_dtype;
typedef ap_int<CONV_LAYER_2_OFM_BITS> conv_layer_2_output_dtype;
typedef ap_ufixed<CONV_LAYER_2_M0_BITS, CONV_LAYER_2_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_2_m0_dtype;

#define CONV_LAYER_3_K                                                        3
#define CONV_LAYER_3_IFM_CH                                                   64
#define CONV_LAYER_3_IFM_DIM                                                  64
#define CONV_LAYER_3_OFM_CH                                                   64
#define CONV_LAYER_3_OFM_DIM                                                  64
#define CONV_LAYER_3_GROUPS                                                   1
#define CONV_LAYER_3_STRIDE                                                   1
#define CONV_LAYER_3_PADDING                                                  1
#define CONV_LAYER_3_SIMD                                                     8
#define CONV_LAYER_3_PE                                                       8
#define CONV_LAYER_3_IFM_BITS                                                 8
#define CONV_LAYER_3_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_3_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_3_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_3_INPUT_ACCESSESS                                          32768
#define CONV_LAYER_3_WEIGHT_BITS                                              8
#define CONV_LAYER_3_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_3_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_3_BIAS_BITS                                                32
#define CONV_LAYER_3_ACC_BITS                                                 32
#define CONV_LAYER_3_ATILES                                                   8
#define CONV_LAYER_3_WTILES                                                   576
#define CONV_LAYER_3_OFM_BITS                                                 8
#define CONV_LAYER_3_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_3_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_3_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_3_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_3_M0                                                       0.0012676437618210912
#define CONV_LAYER_3_M0_BITS                                                  32
#define CONV_LAYER_3_M0_INT_BITS                                              -2
#define CONV_LAYER_3_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_3_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_3_IFM_BITS> conv_layer_3_input_dtype;
typedef ap_int<CONV_LAYER_3_WEIGHT_BITS> conv_layer_3_weight_dtype;
typedef ap_int<CONV_LAYER_3_BIAS_BITS> conv_layer_3_bias_dtype;
typedef ap_int<CONV_LAYER_3_ACC_BITS> conv_layer_3_acc_dtype;
typedef ap_int<CONV_LAYER_3_OFM_BITS> conv_layer_3_output_dtype;
typedef ap_ufixed<CONV_LAYER_3_M0_BITS, CONV_LAYER_3_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_3_m0_dtype;

#define SPLIT_1_SIMD                                                          1
#define SPLIT_1_PE                                                            1
#define SPLIT_1_IFM_BITS                                                      8
#define SPLIT_1_IFM_BITS_ALIGNED                                              8
#define SPLIT_1_INPUT_STREAM_WIDTH                                            8
#define SPLIT_1_INPUT_MEM_WIDTH                                               8
#define SPLIT_1_INPUT_ACCESSESS                                               262144
#define SPLIT_1_OFM_BITS                                                      8
#define SPLIT_1_OFM_BITS_ALIGNED                                              8
#define SPLIT_1_OUTPUT_STREAM_WIDTH                                           8
#define SPLIT_1_OUTPUT_MEM_WIDTH                                              8
#define SPLIT_1_OUTPUT_ACCESSES                                               262144
typedef ap_int<SPLIT_1_IFM_BITS> split_1_input_dtype;
typedef ap_int<SPLIT_1_OFM_BITS> split_1_output_dtype;

#define MAXPOOL_1_SIMD                                                        1
#define MAXPOOL_1_PE                                                          1
#define MAXPOOL_1_K                                                           2
#define MAXPOOL_1_STRIDE                                                      2
#define MAXPOOL_1_IFM_CH                                                      64
#define MAXPOOL_1_IFM_DIM                                                     64
#define MAXPOOL_1_OFM_CH                                                      64
#define MAXPOOL_1_OFM_DIM                                                     32
#define MAXPOOL_1_IFM_BITS                                                    8
#define MAXPOOL_1_IFM_BITS_ALIGNED                                            8
#define MAXPOOL_1_INPUT_STREAM_WIDTH                                          8
#define MAXPOOL_1_INPUT_MEM_WIDTH                                             8
#define MAXPOOL_1_INPUT_ACCESSESS                                             262144
#define MAXPOOL_1_OFM_BITS                                                    8
#define MAXPOOL_1_OFM_BITS_ALIGNED                                            8
#define MAXPOOL_1_OUTPUT_STREAM_WIDTH                                         8
#define MAXPOOL_1_OUTPUT_MEM_WIDTH                                            8
#define MAXPOOL_1_OUTPUT_ACCESSES                                             65536
typedef ap_int<MAXPOOL_1_IFM_BITS> maxpool_1_input_dtype;
typedef ap_int<MAXPOOL_1_OFM_BITS> maxpool_1_output_dtype;

#define CONV_LAYER_4_K                                                        3
#define CONV_LAYER_4_IFM_CH                                                   64
#define CONV_LAYER_4_IFM_DIM                                                  32
#define CONV_LAYER_4_OFM_CH                                                   128
#define CONV_LAYER_4_OFM_DIM                                                  32
#define CONV_LAYER_4_GROUPS                                                   1
#define CONV_LAYER_4_STRIDE                                                   1
#define CONV_LAYER_4_PADDING                                                  1
#define CONV_LAYER_4_SIMD                                                     4
#define CONV_LAYER_4_PE                                                       4
#define CONV_LAYER_4_IFM_BITS                                                 8
#define CONV_LAYER_4_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_4_INPUT_STREAM_WIDTH                                       32
#define CONV_LAYER_4_INPUT_MEM_WIDTH                                          32
#define CONV_LAYER_4_INPUT_ACCESSESS                                          16384
#define CONV_LAYER_4_WEIGHT_BITS                                              8
#define CONV_LAYER_4_WEIGHT_SIMD_WIDTH                                        32
#define CONV_LAYER_4_WEIGHT_SIMD_PE_WIDTH                                     128
#define CONV_LAYER_4_BIAS_BITS                                                32
#define CONV_LAYER_4_ACC_BITS                                                 32
#define CONV_LAYER_4_ATILES                                                   32
#define CONV_LAYER_4_WTILES                                                   4608
#define CONV_LAYER_4_OFM_BITS                                                 8
#define CONV_LAYER_4_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_4_OUTPUT_STREAM_WIDTH                                      32
#define CONV_LAYER_4_OUTPUT_MEM_WIDTH                                         32
#define CONV_LAYER_4_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_4_M0                                                       0.001116143073886633
#define CONV_LAYER_4_M0_BITS                                                  32
#define CONV_LAYER_4_M0_INT_BITS                                              -2
#define CONV_LAYER_4_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_4_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_4_IFM_BITS> conv_layer_4_input_dtype;
typedef ap_int<CONV_LAYER_4_WEIGHT_BITS> conv_layer_4_weight_dtype;
typedef ap_int<CONV_LAYER_4_BIAS_BITS> conv_layer_4_bias_dtype;
typedef ap_int<CONV_LAYER_4_ACC_BITS> conv_layer_4_acc_dtype;
typedef ap_int<CONV_LAYER_4_OFM_BITS> conv_layer_4_output_dtype;
typedef ap_ufixed<CONV_LAYER_4_M0_BITS, CONV_LAYER_4_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_4_m0_dtype;

#define CONV_LAYER_5_K                                                        3
#define CONV_LAYER_5_IFM_CH                                                   128
#define CONV_LAYER_5_IFM_DIM                                                  32
#define CONV_LAYER_5_OFM_CH                                                   128
#define CONV_LAYER_5_OFM_DIM                                                  32
#define CONV_LAYER_5_GROUPS                                                   1
#define CONV_LAYER_5_STRIDE                                                   1
#define CONV_LAYER_5_PADDING                                                  1
#define CONV_LAYER_5_SIMD                                                     8
#define CONV_LAYER_5_PE                                                       8
#define CONV_LAYER_5_IFM_BITS                                                 8
#define CONV_LAYER_5_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_5_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_5_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_5_INPUT_ACCESSESS                                          16384
#define CONV_LAYER_5_WEIGHT_BITS                                              8
#define CONV_LAYER_5_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_5_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_5_BIAS_BITS                                                32
#define CONV_LAYER_5_ACC_BITS                                                 32
#define CONV_LAYER_5_ATILES                                                   16
#define CONV_LAYER_5_WTILES                                                   2304
#define CONV_LAYER_5_OFM_BITS                                                 8
#define CONV_LAYER_5_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_5_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_5_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_5_OUTPUT_ACCESSES                                          16384
#define CONV_LAYER_5_M0                                                       0.0007816230645403266
#define CONV_LAYER_5_M0_BITS                                                  32
#define CONV_LAYER_5_M0_INT_BITS                                              -3
#define CONV_LAYER_5_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_5_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_5_IFM_BITS> conv_layer_5_input_dtype;
typedef ap_int<CONV_LAYER_5_WEIGHT_BITS> conv_layer_5_weight_dtype;
typedef ap_int<CONV_LAYER_5_BIAS_BITS> conv_layer_5_bias_dtype;
typedef ap_int<CONV_LAYER_5_ACC_BITS> conv_layer_5_acc_dtype;
typedef ap_int<CONV_LAYER_5_OFM_BITS> conv_layer_5_output_dtype;
typedef ap_ufixed<CONV_LAYER_5_M0_BITS, CONV_LAYER_5_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_5_m0_dtype;

#define CONVTRANSPOSE_0_K                                                     2
#define CONVTRANSPOSE_0_IFM_CH                                                128
#define CONVTRANSPOSE_0_IFM_DIM                                               32
#define CONVTRANSPOSE_0_OFM_CH                                                64
#define CONVTRANSPOSE_0_OFM_DIM                                               64
#define CONVTRANSPOSE_0_GROUPS                                                1
#define CONVTRANSPOSE_0_STRIDE                                                2
#define CONVTRANSPOSE_0_PADDING                                               0
#define CONVTRANSPOSE_0_SIMD                                                  4
#define CONVTRANSPOSE_0_PE                                                    4
#define CONVTRANSPOSE_0_IFM_BITS                                              8
#define CONVTRANSPOSE_0_IFM_BITS_ALIGNED                                      8
#define CONVTRANSPOSE_0_INPUT_STREAM_WIDTH                                    32
#define CONVTRANSPOSE_0_INPUT_MEM_WIDTH                                       32
#define CONVTRANSPOSE_0_INPUT_ACCESSESS                                       32768
#define CONVTRANSPOSE_0_WEIGHT_BITS                                           8
#define CONVTRANSPOSE_0_WEIGHT_SIMD_WIDTH                                     32
#define CONVTRANSPOSE_0_WEIGHT_SIMD_PE_WIDTH                                  128
#define CONVTRANSPOSE_0_BIAS_BITS                                             32
#define CONVTRANSPOSE_0_ACC_BITS                                              32
#define CONVTRANSPOSE_0_ATILES                                                16
#define CONVTRANSPOSE_0_WTILES                                                2048
#define CONVTRANSPOSE_0_OFM_BITS                                              8
#define CONVTRANSPOSE_0_OFM_BITS_ALIGNED                                      8
#define CONVTRANSPOSE_0_OUTPUT_STREAM_WIDTH                                   32
#define CONVTRANSPOSE_0_OUTPUT_MEM_WIDTH                                      32
#define CONVTRANSPOSE_0_OUTPUT_ACCESSES                                       65536
#define CONVTRANSPOSE_0_M0                                                    0.0018439235864207149
#define CONVTRANSPOSE_0_M0_BITS                                               32
#define CONVTRANSPOSE_0_M0_INT_BITS                                           -2
#define CONVTRANSPOSE_0_INPUT_ZERO_POINT                                      -128
#define CONVTRANSPOSE_0_OUTPUT_ZERO_POINT                                     -3
typedef ap_int<CONVTRANSPOSE_0_IFM_BITS> convtranspose_0_input_dtype;
typedef ap_int<CONVTRANSPOSE_0_WEIGHT_BITS> convtranspose_0_weight_dtype;
typedef ap_int<CONVTRANSPOSE_0_BIAS_BITS> convtranspose_0_bias_dtype;
typedef ap_int<CONVTRANSPOSE_0_ACC_BITS> convtranspose_0_acc_dtype;
typedef ap_int<CONVTRANSPOSE_0_OFM_BITS> convtranspose_0_output_dtype;
typedef ap_ufixed<CONVTRANSPOSE_0_M0_BITS, CONVTRANSPOSE_0_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> convtranspose_0_m0_dtype;

#define CONCAT_0_SIMD                                                         1
#define CONCAT_0_PE                                                           1
#define CONCAT_0_IFM_CH                                                       64
#define CONCAT_0_IFM_DIM                                                      64
#define CONCAT_0_IFM_BITS                                                     8
#define CONCAT_0_OFM_BITS                                                     8
#define CONCAT_0_INPUT_STREAM_WIDTH                                           8
#define CONCAT_0_OFM_BITS_ALIGNED                                             32
#define CONCAT_0_OUTPUT_STREAM_WIDTH                                          8
#define CONCAT_0_OUTPUT_ACCESSES                                              524288
#define CONCAT_0_0_M0                                                         0.7145804762840271
#define CONCAT_0_0_INPUT_ZERO_POINT                                           36.46630096435547
#define CONCAT_0_1_M0                                                         0.5844913125038147
#define CONCAT_0_1_INPUT_ZERO_POINT                                           -53.246526062488556
#define CONCAT_0_SCALE_BITS                                                   32
#define CONCAT_0_SCALE_INT_BITS                                               0
#define CONCAT_0_SHIFT_BITS                                                   32
#define CONCAT_0_SHIFT_INT_BITS                                               7
typedef ap_ufixed<CONCAT_0_SCALE_BITS,CONCAT_0_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_0_scale_dtype;
typedef ap_fixed<CONCAT_0_SHIFT_BITS,CONCAT_0_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_0_shift_dtype;
typedef ap_int<CONCAT_0_IFM_BITS> concat_0_input_dtype;
typedef ap_int<CONCAT_0_OFM_BITS> concat_0_output_dtype;

#define CONV_LAYER_6_K                                                        3
#define CONV_LAYER_6_IFM_CH                                                   128
#define CONV_LAYER_6_IFM_DIM                                                  64
#define CONV_LAYER_6_OFM_CH                                                   64
#define CONV_LAYER_6_OFM_DIM                                                  64
#define CONV_LAYER_6_GROUPS                                                   1
#define CONV_LAYER_6_STRIDE                                                   1
#define CONV_LAYER_6_PADDING                                                  1
#define CONV_LAYER_6_SIMD                                                     8
#define CONV_LAYER_6_PE                                                       8
#define CONV_LAYER_6_IFM_BITS                                                 8
#define CONV_LAYER_6_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_6_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_6_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_6_INPUT_ACCESSESS                                          65536
#define CONV_LAYER_6_WEIGHT_BITS                                              8
#define CONV_LAYER_6_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_6_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_6_BIAS_BITS                                                32
#define CONV_LAYER_6_ACC_BITS                                                 32
#define CONV_LAYER_6_ATILES                                                   8
#define CONV_LAYER_6_WTILES                                                   1152
#define CONV_LAYER_6_OFM_BITS                                                 8
#define CONV_LAYER_6_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_6_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_6_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_6_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_6_M0                                                       0.0009193118312396109
#define CONV_LAYER_6_M0_BITS                                                  32
#define CONV_LAYER_6_M0_INT_BITS                                              -3
#define CONV_LAYER_6_INPUT_ZERO_POINT                                         -55
#define CONV_LAYER_6_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_6_IFM_BITS> conv_layer_6_input_dtype;
typedef ap_int<CONV_LAYER_6_WEIGHT_BITS> conv_layer_6_weight_dtype;
typedef ap_int<CONV_LAYER_6_BIAS_BITS> conv_layer_6_bias_dtype;
typedef ap_int<CONV_LAYER_6_ACC_BITS> conv_layer_6_acc_dtype;
typedef ap_int<CONV_LAYER_6_OFM_BITS> conv_layer_6_output_dtype;
typedef ap_ufixed<CONV_LAYER_6_M0_BITS, CONV_LAYER_6_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_6_m0_dtype;

#define CONV_LAYER_7_K                                                        3
#define CONV_LAYER_7_IFM_CH                                                   64
#define CONV_LAYER_7_IFM_DIM                                                  64
#define CONV_LAYER_7_OFM_CH                                                   64
#define CONV_LAYER_7_OFM_DIM                                                  64
#define CONV_LAYER_7_GROUPS                                                   1
#define CONV_LAYER_7_STRIDE                                                   1
#define CONV_LAYER_7_PADDING                                                  1
#define CONV_LAYER_7_SIMD                                                     8
#define CONV_LAYER_7_PE                                                       8
#define CONV_LAYER_7_IFM_BITS                                                 8
#define CONV_LAYER_7_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_7_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_7_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_7_INPUT_ACCESSESS                                          32768
#define CONV_LAYER_7_WEIGHT_BITS                                              8
#define CONV_LAYER_7_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_7_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_7_BIAS_BITS                                                32
#define CONV_LAYER_7_ACC_BITS                                                 32
#define CONV_LAYER_7_ATILES                                                   8
#define CONV_LAYER_7_WTILES                                                   576
#define CONV_LAYER_7_OFM_BITS                                                 8
#define CONV_LAYER_7_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_7_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_7_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_7_OUTPUT_ACCESSES                                          32768
#define CONV_LAYER_7_M0                                                       0.0008236305438913405
#define CONV_LAYER_7_M0_BITS                                                  32
#define CONV_LAYER_7_M0_INT_BITS                                              -3
#define CONV_LAYER_7_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_7_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_7_IFM_BITS> conv_layer_7_input_dtype;
typedef ap_int<CONV_LAYER_7_WEIGHT_BITS> conv_layer_7_weight_dtype;
typedef ap_int<CONV_LAYER_7_BIAS_BITS> conv_layer_7_bias_dtype;
typedef ap_int<CONV_LAYER_7_ACC_BITS> conv_layer_7_acc_dtype;
typedef ap_int<CONV_LAYER_7_OFM_BITS> conv_layer_7_output_dtype;
typedef ap_ufixed<CONV_LAYER_7_M0_BITS, CONV_LAYER_7_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_7_m0_dtype;

#define CONVTRANSPOSE_1_K                                                     2
#define CONVTRANSPOSE_1_IFM_CH                                                64
#define CONVTRANSPOSE_1_IFM_DIM                                               64
#define CONVTRANSPOSE_1_OFM_CH                                                32
#define CONVTRANSPOSE_1_OFM_DIM                                               128
#define CONVTRANSPOSE_1_GROUPS                                                1
#define CONVTRANSPOSE_1_STRIDE                                                2
#define CONVTRANSPOSE_1_PADDING                                               0
#define CONVTRANSPOSE_1_SIMD                                                  4
#define CONVTRANSPOSE_1_PE                                                    4
#define CONVTRANSPOSE_1_IFM_BITS                                              8
#define CONVTRANSPOSE_1_IFM_BITS_ALIGNED                                      8
#define CONVTRANSPOSE_1_INPUT_STREAM_WIDTH                                    32
#define CONVTRANSPOSE_1_INPUT_MEM_WIDTH                                       32
#define CONVTRANSPOSE_1_INPUT_ACCESSESS                                       65536
#define CONVTRANSPOSE_1_WEIGHT_BITS                                           8
#define CONVTRANSPOSE_1_WEIGHT_SIMD_WIDTH                                     32
#define CONVTRANSPOSE_1_WEIGHT_SIMD_PE_WIDTH                                  128
#define CONVTRANSPOSE_1_BIAS_BITS                                             32
#define CONVTRANSPOSE_1_ACC_BITS                                              32
#define CONVTRANSPOSE_1_ATILES                                                8
#define CONVTRANSPOSE_1_WTILES                                                512
#define CONVTRANSPOSE_1_OFM_BITS                                              8
#define CONVTRANSPOSE_1_OFM_BITS_ALIGNED                                      8
#define CONVTRANSPOSE_1_OUTPUT_STREAM_WIDTH                                   32
#define CONVTRANSPOSE_1_OUTPUT_MEM_WIDTH                                      32
#define CONVTRANSPOSE_1_OUTPUT_ACCESSES                                       131072
#define CONVTRANSPOSE_1_M0                                                    0.0012748289154842496
#define CONVTRANSPOSE_1_M0_BITS                                               32
#define CONVTRANSPOSE_1_M0_INT_BITS                                           -2
#define CONVTRANSPOSE_1_INPUT_ZERO_POINT                                      -128
#define CONVTRANSPOSE_1_OUTPUT_ZERO_POINT                                     2
typedef ap_int<CONVTRANSPOSE_1_IFM_BITS> convtranspose_1_input_dtype;
typedef ap_int<CONVTRANSPOSE_1_WEIGHT_BITS> convtranspose_1_weight_dtype;
typedef ap_int<CONVTRANSPOSE_1_BIAS_BITS> convtranspose_1_bias_dtype;
typedef ap_int<CONVTRANSPOSE_1_ACC_BITS> convtranspose_1_acc_dtype;
typedef ap_int<CONVTRANSPOSE_1_OFM_BITS> convtranspose_1_output_dtype;
typedef ap_ufixed<CONVTRANSPOSE_1_M0_BITS, CONVTRANSPOSE_1_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> convtranspose_1_m0_dtype;

#define CONCAT_1_SIMD                                                         1
#define CONCAT_1_PE                                                           1
#define CONCAT_1_IFM_CH                                                       32
#define CONCAT_1_IFM_DIM                                                      128
#define CONCAT_1_IFM_BITS                                                     8
#define CONCAT_1_OFM_BITS                                                     8
#define CONCAT_1_INPUT_STREAM_WIDTH                                           8
#define CONCAT_1_OFM_BITS_ALIGNED                                             32
#define CONCAT_1_OUTPUT_STREAM_WIDTH                                          8
#define CONCAT_1_OUTPUT_ACCESSES                                              1048576
#define CONCAT_1_0_M0                                                         0.5313746333122253
#define CONCAT_1_0_INPUT_ZERO_POINT                                           59.015953063964844
#define CONCAT_1_1_M0                                                         0.9207453727722168
#define CONCAT_1_1_INPUT_ZERO_POINT                                           -10.841490745544434
#define CONCAT_1_SCALE_BITS                                                   32
#define CONCAT_1_SCALE_INT_BITS                                               0
#define CONCAT_1_SHIFT_BITS                                                   32
#define CONCAT_1_SHIFT_INT_BITS                                               7
typedef ap_ufixed<CONCAT_1_SCALE_BITS,CONCAT_1_SCALE_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_1_scale_dtype;
typedef ap_fixed<CONCAT_1_SHIFT_BITS,CONCAT_1_SHIFT_INT_BITS,AP_RND_ZERO,AP_WRAP> concat_1_shift_dtype;
typedef ap_int<CONCAT_1_IFM_BITS> concat_1_input_dtype;
typedef ap_int<CONCAT_1_OFM_BITS> concat_1_output_dtype;

#define CONV_LAYER_8_K                                                        3
#define CONV_LAYER_8_IFM_CH                                                   64
#define CONV_LAYER_8_IFM_DIM                                                  128
#define CONV_LAYER_8_OFM_CH                                                   32
#define CONV_LAYER_8_OFM_DIM                                                  128
#define CONV_LAYER_8_GROUPS                                                   1
#define CONV_LAYER_8_STRIDE                                                   1
#define CONV_LAYER_8_PADDING                                                  1
#define CONV_LAYER_8_SIMD                                                     8
#define CONV_LAYER_8_PE                                                       8
#define CONV_LAYER_8_IFM_BITS                                                 8
#define CONV_LAYER_8_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_8_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_8_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_8_INPUT_ACCESSESS                                          131072
#define CONV_LAYER_8_WEIGHT_BITS                                              8
#define CONV_LAYER_8_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_8_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_8_BIAS_BITS                                                32
#define CONV_LAYER_8_ACC_BITS                                                 32
#define CONV_LAYER_8_ATILES                                                   4
#define CONV_LAYER_8_WTILES                                                   288
#define CONV_LAYER_8_OFM_BITS                                                 8
#define CONV_LAYER_8_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_8_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_8_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_8_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_8_M0                                                       0.0009364115539938211
#define CONV_LAYER_8_M0_BITS                                                  32
#define CONV_LAYER_8_M0_INT_BITS                                              -3
#define CONV_LAYER_8_INPUT_ZERO_POINT                                         -9
#define CONV_LAYER_8_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_8_IFM_BITS> conv_layer_8_input_dtype;
typedef ap_int<CONV_LAYER_8_WEIGHT_BITS> conv_layer_8_weight_dtype;
typedef ap_int<CONV_LAYER_8_BIAS_BITS> conv_layer_8_bias_dtype;
typedef ap_int<CONV_LAYER_8_ACC_BITS> conv_layer_8_acc_dtype;
typedef ap_int<CONV_LAYER_8_OFM_BITS> conv_layer_8_output_dtype;
typedef ap_ufixed<CONV_LAYER_8_M0_BITS, CONV_LAYER_8_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_8_m0_dtype;

#define CONV_LAYER_9_K                                                        3
#define CONV_LAYER_9_IFM_CH                                                   32
#define CONV_LAYER_9_IFM_DIM                                                  128
#define CONV_LAYER_9_OFM_CH                                                   32
#define CONV_LAYER_9_OFM_DIM                                                  128
#define CONV_LAYER_9_GROUPS                                                   1
#define CONV_LAYER_9_STRIDE                                                   1
#define CONV_LAYER_9_PADDING                                                  1
#define CONV_LAYER_9_SIMD                                                     8
#define CONV_LAYER_9_PE                                                       8
#define CONV_LAYER_9_IFM_BITS                                                 8
#define CONV_LAYER_9_IFM_BITS_ALIGNED                                         8
#define CONV_LAYER_9_INPUT_STREAM_WIDTH                                       64
#define CONV_LAYER_9_INPUT_MEM_WIDTH                                          64
#define CONV_LAYER_9_INPUT_ACCESSESS                                          65536
#define CONV_LAYER_9_WEIGHT_BITS                                              8
#define CONV_LAYER_9_WEIGHT_SIMD_WIDTH                                        64
#define CONV_LAYER_9_WEIGHT_SIMD_PE_WIDTH                                     512
#define CONV_LAYER_9_BIAS_BITS                                                32
#define CONV_LAYER_9_ACC_BITS                                                 32
#define CONV_LAYER_9_ATILES                                                   4
#define CONV_LAYER_9_WTILES                                                   144
#define CONV_LAYER_9_OFM_BITS                                                 8
#define CONV_LAYER_9_OFM_BITS_ALIGNED                                         8
#define CONV_LAYER_9_OUTPUT_STREAM_WIDTH                                      64
#define CONV_LAYER_9_OUTPUT_MEM_WIDTH                                         64
#define CONV_LAYER_9_OUTPUT_ACCESSES                                          65536
#define CONV_LAYER_9_M0                                                       0.0005830778973177075
#define CONV_LAYER_9_M0_BITS                                                  32
#define CONV_LAYER_9_M0_INT_BITS                                              -3
#define CONV_LAYER_9_INPUT_ZERO_POINT                                         -128
#define CONV_LAYER_9_OUTPUT_ZERO_POINT                                        -128
typedef ap_int<CONV_LAYER_9_IFM_BITS> conv_layer_9_input_dtype;
typedef ap_int<CONV_LAYER_9_WEIGHT_BITS> conv_layer_9_weight_dtype;
typedef ap_int<CONV_LAYER_9_BIAS_BITS> conv_layer_9_bias_dtype;
typedef ap_int<CONV_LAYER_9_ACC_BITS> conv_layer_9_acc_dtype;
typedef ap_int<CONV_LAYER_9_OFM_BITS> conv_layer_9_output_dtype;
typedef ap_ufixed<CONV_LAYER_9_M0_BITS, CONV_LAYER_9_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_9_m0_dtype;

#define CONV_LAYER_10_K                                                       1
#define CONV_LAYER_10_IFM_CH                                                  32
#define CONV_LAYER_10_IFM_DIM                                                 128
#define CONV_LAYER_10_OFM_CH                                                  11
#define CONV_LAYER_10_OFM_DIM                                                 128
#define CONV_LAYER_10_GROUPS                                                  1
#define CONV_LAYER_10_STRIDE                                                  1
#define CONV_LAYER_10_PADDING                                                 0
#define CONV_LAYER_10_SIMD                                                    1
#define CONV_LAYER_10_PE                                                      1
#define CONV_LAYER_10_IFM_BITS                                                8
#define CONV_LAYER_10_IFM_BITS_ALIGNED                                        8
#define CONV_LAYER_10_INPUT_STREAM_WIDTH                                      8
#define CONV_LAYER_10_INPUT_MEM_WIDTH                                         8
#define CONV_LAYER_10_INPUT_ACCESSESS                                         524288
#define CONV_LAYER_10_WEIGHT_BITS                                             8
#define CONV_LAYER_10_WEIGHT_SIMD_WIDTH                                       8
#define CONV_LAYER_10_WEIGHT_SIMD_PE_WIDTH                                    8
#define CONV_LAYER_10_BIAS_BITS                                               32
#define CONV_LAYER_10_ACC_BITS                                                32
#define CONV_LAYER_10_ATILES                                                  11
#define CONV_LAYER_10_WTILES                                                  352
#define CONV_LAYER_10_OFM_BITS                                                8
#define CONV_LAYER_10_OFM_BITS_ALIGNED                                        8
#define CONV_LAYER_10_OUTPUT_STREAM_WIDTH                                     8
#define CONV_LAYER_10_OUTPUT_MEM_WIDTH                                        8
#define CONV_LAYER_10_OUTPUT_ACCESSES                                         180224
#define CONV_LAYER_10_M0                                                      0.0019102011574432254
#define CONV_LAYER_10_M0_BITS                                                 32
#define CONV_LAYER_10_M0_INT_BITS                                             -2
#define CONV_LAYER_10_INPUT_ZERO_POINT                                        -128
#define CONV_LAYER_10_OUTPUT_ZERO_POINT                                       24
typedef ap_int<CONV_LAYER_10_IFM_BITS> conv_layer_10_input_dtype;
typedef ap_int<CONV_LAYER_10_WEIGHT_BITS> conv_layer_10_weight_dtype;
typedef ap_int<CONV_LAYER_10_BIAS_BITS> conv_layer_10_bias_dtype;
typedef ap_int<CONV_LAYER_10_ACC_BITS> conv_layer_10_acc_dtype;
typedef ap_int<CONV_LAYER_10_OFM_BITS> conv_layer_10_output_dtype;
typedef ap_ufixed<CONV_LAYER_10_M0_BITS, CONV_LAYER_10_M0_INT_BITS, AP_RND_ZERO, AP_WRAP> conv_layer_10_m0_dtype;

const int num_packed_outputs = 11264;
#define CONV_LAYER_10_TOP_LEVEL_OUTPUT_BITS                                   8
typedef ap_int<CONV_LAYER_10_TOP_LEVEL_OUTPUT_BITS> conv_layer_10_top_level_output_dtype;

#define Reps 1


#endif